dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.3.2

compiler:
  solc:
    version: "0.8.0"
    settings:
      optimizer:
        enabled: true
        runs: 200

networks:
  taraxa:
    mainnet:
      host: https://rpc.mainnet.taraxa.io
      explorer: https://mainnet.explorer.taraxa.io/
      chain_id: 841
    testnet:
      host: https://rpc.testnet.taraxa.io
      explorer: https://explorer.testnet.taraxa.io/
      chain_id: 842
