dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.0
  - smartcontractkit/chainlink@0.2.2

compiler:
  solc:
    version: "0.8.0"
    settings:
      optimizer:
        enabled: true
        runs: 200

networks:
  taraxa:
    mainnet:
      host: https://rpc.mainnet.taraxa.io
      explorer: https://mainnet.explorer.taraxa.io/
      chain_id: 841
    testnet:
      host: https://rpc.testnet.taraxa.io
      explorer: https://testnet.explorer.taraxa.io/
      chain_id: 842
