dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

compiler:
  solc:
    version: 0.8.0

networks:
  development:
    gas_limit: auto
    gas_price: auto

wallets:
  from_key: ${PRIVATE_KEY}
